/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dd_da
 */
public class TriangulosVerify extends javax.swing.JFrame {

    /**
     * Creates new form TriangulosVerify
     */
    public TriangulosVerify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        sR1 = new javax.swing.JSlider();
        sR2 = new javax.swing.JSlider();
        sR3 = new javax.swing.JSlider();
        lblL1 = new javax.swing.JLabel();
        lblL2 = new javax.swing.JLabel();
        lblL3 = new javax.swing.JLabel();
        btnVerify = new javax.swing.JButton();
        lblRes = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tring.png"))); // NOI18N

        sR1.setValue(0);
        sR1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sR1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sR1StateChanged(evt);
            }
        });

        sR2.setValue(0);
        sR2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sR2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sR2StateChanged(evt);
            }
        });

        sR3.setValue(0);
        sR3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sR3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sR3StateChanged(evt);
            }
        });

        lblL1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblL1.setText("0");

        lblL2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblL2.setText("0");

        lblL3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblL3.setText("0");

        btnVerify.setFont(new java.awt.Font("RomanD", 0, 12)); // NOI18N
        btnVerify.setText("Verificar");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        lblRes.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        lblRes.setForeground(new java.awt.Color(51, 102, 0));
        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(sR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblL1)
                            .addComponent(lblL2)
                            .addComponent(lblL3)))
                    .addComponent(lblRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblL1)
                                .addGap(10, 10, 10)
                                .addComponent(lblL2)
                                .addGap(10, 10, 10)
                                .addComponent(lblL3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(sR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(sR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerify)
                        .addGap(35, 35, 35)
                        .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        int a = sR1.getValue();
        int b = sR2.getValue();
        int c = sR3.getValue();
        if ((a==0)||(b==0)||(c==0)){
            lblRes.setText("Não forma um triângulo");
        }else if (a==b){
            if (a==c){
                lblRes.setText("Equilátero");
            } else{
                lblRes.setText("Isósceles");
            }
        } else if ((b==c)||(a==c)){
            lblRes.setText("Isósceles");
        }else {lblRes.setText("Escaleno");}
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void sR1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sR1StateChanged
        // TODO add your handling code here:
        lblL1.setText(Integer.toString(sR1.getValue()));
    }//GEN-LAST:event_sR1StateChanged

    private void sR2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sR2StateChanged
        // TODO add your handling code here:
        lblL2.setText(Integer.toString(sR2.getValue()));
    }//GEN-LAST:event_sR2StateChanged

    private void sR3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sR3StateChanged
        // TODO add your handling code here:
        lblL3.setText(Integer.toString(sR3.getValue()));
    }//GEN-LAST:event_sR3StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangulosVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangulosVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangulosVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangulosVerify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangulosVerify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblL1;
    private javax.swing.JLabel lblL2;
    private javax.swing.JLabel lblL3;
    private javax.swing.JLabel lblRes;
    private javax.swing.JSlider sR1;
    private javax.swing.JSlider sR2;
    private javax.swing.JSlider sR3;
    // End of variables declaration//GEN-END:variables
}
